name: pdftr

services:
  # PostgreSQL Database with Enhanced Configuration
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: pdftr
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=en_US.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d pdftr"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pdftr_default
    restart: unless-stopped

  # Redis Cache and Message Broker
  cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pdftr_default
    restart: unless-stopped

  # FastAPI Backend
  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/pdftr
      - REDIS_URL=redis://cache:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENVIRONMENT=production
      - DEBUG=false
      - CORS_ORIGINS=https://pdf.edcopo.info,https://apipdf.edcopo.info
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - pdftr_default
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Next.js Frontend
  web:
    build: 
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: https://apipdf.edcopo.info
        NEXT_PUBLIC_APP_URL: https://pdf.edcopo.info
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Both browser and server-side use dedicated API subdomain through Caddy
      - NEXT_PUBLIC_API_URL=https://apipdf.edcopo.info
      - NEXT_PUBLIC_APP_URL=https://pdf.edcopo.info
    depends_on:
      - api
    networks:
      - pdftr_default
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Celery Worker for Background Tasks
  worker:
    build: ./backend
    command: celery -A app.workers.celery_worker.celery_app worker --loglevel=info --concurrency=4
    environment:
      - DATABASE_URL=postgresql://user:password@db/pdftr
      - REDIS_URL=redis://cache:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENVIRONMENT=production
    depends_on:
      - api
      - cache
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - pdftr_default
    restart: unless-stopped
    deploy:
      replicas: 2

  # Celery Flower for Monitoring
  monitor:
    build: ./backend
    command: celery -A app.workers.celery_worker.celery_app flower --port=5555 --broker=redis://cache:6379/0
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://cache:6379/0
      - FLOWER_BASIC_AUTH=admin:${FLOWER_PASSWORD}
    depends_on:
      - cache
      - worker
    networks:
      - pdftr_default
    restart: unless-stopped

  # Caddy reverse proxy and HTTPS termination
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./uploads:/var/www/uploads
      - ./logs:/var/log/caddy
    environment:
      - CADDY_INGRESS_NETWORKS=pdf_translation_platform_default
    networks:
      - pdftr_default
    restart: unless-stopped
    depends_on:
      - api
      - web
      - monitor

  # Optional: Database Backup Service
  backup:
    image: postgres:15-alpine
    environment:
      - PGPASSWORD=password
    volumes:
      - ./backups:/backups
      - postgres_data:/var/lib/postgresql/data
    command: |
      sh -c '
        while true; do
          pg_dump -h db -U user pdftr > /backups/backup_$$(date +%Y%m%d_%H%M%S).sql
          find /backups -name "backup_*.sql" -mtime +7 -delete
          sleep 86400
        done
      '
    depends_on:
      - db
    networks:
      - pdftr_default
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  caddy_data:
  caddy_config:

networks:
  pdftr_default:
    driver: bridge