---
name: Bug Report
about: Create a report to help us improve
title: '[BUG] '
labels: bug
assignees: ''

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment (please complete the following information):**
 - OS: [e.g. macOS, Windows, Linux]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]
 - Docker version [e.g. 20.10.0]

**Backend Logs**
```
Paste any relevant backend logs here
```

**Frontend Console Logs**
```
Paste any relevant frontend console logs here
```

**Additional context**
Add any other context about the problem here.

**Translation Specific**
- [ ] PDF upload issue
- [ ] Translation quality issue
- [ ] Performance issue
- [ ] API error
- [ ] Database issue
- [ ] Celery worker issue
